export const LOADING_SCREEN = 'lxm.LoadingScreen'
export const LOGIN_SCREEN = 'lxm.LoginScreen'
export const HOME_SCREEN = 'lxm.HomeScreen'
export const SEARCH_SCREEN = 'lxm.SearchScreen'
export const PLAY_DETAIL_SCREEN = 'lxm.PlayDetailScreen'
export const SONGLIST_DETAIL_SCREEN = 'lxm.SonglistDetailScreen'
export const ARTIST_DETAIL_SCREEN = 'lxm.ArtistDetailScreen'
export const ALBUM_DETAIL_SCREEN = 'lxm.AlbumDetailScreen'
export const COMMENT_SCREEN = 'lxm.CommentScreen'
export const VERSION_MODAL = 'lxm.VersionModal'
export const PACT_MODAL = 'lxm.PactModal'
export const SYNC_MODE_MODAL = 'lxm.SyncModeModal'
// export const SETTING_SCREEN = 'lxm.SettingScreen'
// export const TOAST_SCREEN = 'lxm.ToastScreen'

